// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH5NZEkr8OYBKA6UapeVkoB2-jIrzwTsw',
    appId: '1:319321521259:web:26baa3f2f96fd2703e052e',
    messagingSenderId: '319321521259',
    projectId: 'std-mgt-sys-7bd36',
    authDomain: 'std-mgt-sys-7bd36.firebaseapp.com',
    storageBucket: 'std-mgt-sys-7bd36.appspot.com',
    measurementId: 'G-ELJHGW1YE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzO_HdNDFY8fwRNt-JsIBvcHUxphPhRGI',
    appId: '1:319321521259:android:49cdad68593eec873e052e',
    messagingSenderId: '319321521259',
    projectId: 'std-mgt-sys-7bd36',
    storageBucket: 'std-mgt-sys-7bd36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs0pW48nnc61xrPhiOPtpb8OwmBfgFf64',
    appId: '1:319321521259:ios:4021c401196cb58d3e052e',
    messagingSenderId: '319321521259',
    projectId: 'std-mgt-sys-7bd36',
    storageBucket: 'std-mgt-sys-7bd36.appspot.com',
    iosClientId: '319321521259-0oo3jm3lhd09ibdunc9cgq89vq5kup3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.stdMgtSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs0pW48nnc61xrPhiOPtpb8OwmBfgFf64',
    appId: '1:319321521259:ios:6ba012e07a415ed83e052e',
    messagingSenderId: '319321521259',
    projectId: 'std-mgt-sys-7bd36',
    storageBucket: 'std-mgt-sys-7bd36.appspot.com',
    iosClientId: '319321521259-a4d4227crhdd4rimd9lspmlh9gd30hhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.stdMgtSys.RunnerTests',
  );
}
